#默认使用配置
spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://192.168.1.110:3306/test
    username: root
    password: Root@123ASD
    driver-class-name: com.mysql.jdbc.Driver
#公共配置与profiles选择无关
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.whf.webmagic.entity

server:
  port: 8080

